name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 115-pc:latest
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/115-pc:latest
